name: getx_checkers
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  audioplayers: ^6.1.0
  button_animations: ^2.0.0+3
  confetti: ^0.8.0
  flutter:
    sdk: flutter
  flutter_plus: ^1.0.1
  get: ^4.6.6
  getwidget: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    #- assets/sounds/move.mp3
    #- assets/sounds/capture.mp3
    #- assets/sounds/win.mp3
    #- assets/sounds/defeat.mp3

get_cli:
    sub_folder: false  
